# Generated by Django 3.2.4 on 2021-06-18 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='introdution',
            new_name='introduction',
        ),
    ]
